Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
s.loc[['2000','2005','2010']]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[101], line 1[0m
[0;32m----> 1[0m [43ms[49m[38;5;241;43m.[39;49m[43mloc[49m[43m[[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43m2000[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43m2005[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43m2010[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py:1191[0m, in [0;36m_LocationIndexer.__getitem__[0;34m(self, key)[0m
[1;32m   1189[0m maybe_callable [38;5;241m=[39m com[38;5;241m.[39mapply_if_callable(key, [38;5;28mself[39m[38;5;241m.[39mobj)
[1;32m   1190[0m maybe_callable [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_check_deprecated_callable_usage(key, maybe_callable)
[0;32m-> 1191[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_axis[49m[43m([49m[43mmaybe_callable[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py:1420[0m, in [0;36m_LocIndexer._getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1417[0m     [38;5;28;01mif[39;00m [38;5;28mhasattr[39m(key, [38;5;124m"[39m[38;5;124mndim[39m[38;5;124m"[39m) [38;5;129;01mand[39;00m key[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   1418[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mCannot index with multidimensional key[39m[38;5;124m"[39m)
[0;32m-> 1420[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_iterable[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m
[1;32m   1422[0m [38;5;66;03m# nested tuple slicing[39;00m
[1;32m   1423[0m [38;5;28;01mif[39;00m is_nested_tuple(key, labels):

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py:1360[0m, in [0;36m_LocIndexer._getitem_iterable[0;34m(self, key, axis)[0m
[1;32m   1357[0m [38;5;28mself[39m[38;5;241m.[39m_validate_key(key, axis)
[1;32m   1359[0m [38;5;66;03m# A collection of keys[39;00m
[0;32m-> 1360[0m keyarr, indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_listlike_indexer[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[43m)[49m
[1;32m   1361[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_reindex_with_indexers(
[1;32m   1362[0m     {axis: [keyarr, indexer]}, copy[38;5;241m=[39m[38;5;28;01mTrue[39;00m, allow_dups[38;5;241m=[39m[38;5;28;01mTrue[39;00m
[1;32m   1363[0m )

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py:1558[0m, in [0;36m_LocIndexer._get_listlike_indexer[0;34m(self, key, axis)[0m
[1;32m   1555[0m ax [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_axis(axis)
[1;32m   1556[0m axis_name [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_axis_name(axis)
[0;32m-> 1558[0m keyarr, indexer [38;5;241m=[39m [43max[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[1;32m   1560[0m [38;5;28;01mreturn[39;00m keyarr, indexer

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py:6200[0m, in [0;36mIndex._get_indexer_strict[0;34m(self, key, axis_name)[0m
[1;32m   6197[0m [38;5;28;01melse[39;00m:
[1;32m   6198[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[0;32m-> 6200[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[1;32m   6202[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[1;32m   6203[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[1;32m   6204[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexes/base.py:6252[0m, in [0;36mIndex._raise_if_missing[0;34m(self, key, indexer, axis_name)[0m
[1;32m   6249[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[1;32m   6251[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[0;32m-> 6252[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[0;31mKeyError[0m: "['2010'] not in index"

